# Usar a imagem base oficial do PostgreSQL
FROM postgres:13

# Etapa opcional: Definir senha para o usuário 'postgres'
ENV POSTGRES_PASSWORD=mysecretpassword

# Etapa opcional: Criar um banco de dados padrão
ENV POSTGRES_DB=mydatabase

# Expor a porta 5432 (padrão do PostgreSQL)
EXPOSE 5432
