name: Build and Test Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Front-End Docker image
        run: docker build -t my-react-app ./frontend

      - name: Build Back-End Docker image
        run: docker build -t my-node-app ./backend

      - name: Run Front-End Tests
        run: |
          docker run --rm my-react-app npm run test

      - name: Run Back-End Tests
        run: |
          docker run --rm my-node-app npm run test
