name: Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Front-End Docker image
        run: docker build -t myusername/my-react-app ./frontend

      - name: Build Back-End Docker image
        run: docker build -t myusername/my-node-app ./backend

      - name: Push Front-End image to Docker Hub
        run: docker push myusername/my-react-app

      - name: Push Back-End image to Docker Hub
        run: docker push myusername/my-node-app

      - name: Deploy to Production
        run: |
          echo "Deploying to production server..."
          # Aqui você pode colocar comandos para fazer o deploy no servidor real
